name: 'Recovery Compiler For Github Actions' 
author: 'ElytrA8' 
description: 'Universal Recovery Compiler'

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/build.sh
      name: 'Build Recovery'
      shell: bash

branding:
  icon: 'box'
  color: 'black'
